graph LR

    style tx2 fill:#844
    style User0 fill:#444
    style User1 fill:#444
    style ServiceContract0 fill:#559
    style ServiceContract1 fill:#559

    subgraph on-chain
    %% tx2 - user reserves tokens for service charge
    tx2("tx2")
    %% inputs
    User0("User: BCA1 25") -->|"deposit 5"| tx2
    ServiceContract0("Service Contract: BCA1 0") --> tx2

    %% outputs
    tx2 --> User1("User: BCA1 20")
    tx2 --> ServiceContract1("Service Contract: BCA1 5")
    end
