graph TD 

    style tx3 fill:#844
    style µpay fill:#626
    style User0 fill:#444
    style User1 fill:#444
    style User2 fill:#444
    style Service0 fill:#559
    style Service1 fill:#559
    style Service2 fill:#559
    style Service3 fill:#559

    subgraph service smart contract
    %% µpay - services debit the user account for usage
    µpay("micro-payment")
    User0(User: BCA1 4.8) -.->|dt = -0.1| µpay
    Service0(Provider: BCA1 0) -.->|dt = +0.1| µpay
    µpay -.-> User1(User: BCA1 4.7)
    µpay -.-> Service1(Provider: BCA1 0.1)
    end

    subgraph withdrawal
    tx3("tx3")
    User1(User: BCA1 4.7) -.-> tx3
    Service1(Provider: BCA1 0.1) -.-> tx3
    tx3 -.-> User2(User: BCA1 4.7)
    tx3 -.-> Service2(Provider: BCA1 0)
    tx3 -.->|withdrawal| Service3(Provider': BCA1 0.1)
    end